# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name : Docker-CI
trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: 'carlospanarello:$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      name: 'Docker_Login'
      inputs:
        containerRegistry: 'Docker_Hub_Unyleya_Projects'
        command: 'login'
    - task: Docker@2
      name: 'Docker_build'
      displayName: Build an docker image 
      inputs:
        containerRegistry: 'Docker_Hub_Unyleya_Projects'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      name: 'Docker_push'
      displayName: Push docker image to docker hub
      inputs:
        containerRegistry: 'Docker_Hub_Unyleya_Projects'
        repository: 'panarello/unyleya-devops'
        command: 'push'
