# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-latest'

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker_Hub_Unyleya_Projects'
        repository: 'unyleya-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'