# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name : Docker-CI
trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      name: 'Docker_Login'
      inputs:
        containerRegistry: 'Docker_Hub_Unyleya_Projects'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker_Hub_Unyleya_Projects'
        repository: 'panarello/unyleya-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(Build.BuildId)

